server:
  port: 9000
# Spring Cloud Config
spring:
  application:
    name: discovery-springcloud-example-scconfig-server
  profiles:
    active:
      native
  cloud:
    config:
      server:
        bootstrap: true
        native:
          search-locations:
            classpath:/NepxionDiscovery/
      fail-fast: true
# Spring Cloud Config config for rule
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: 
    password: 
    virtual-host:          
# Eureka config for discovery
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:9528/eureka/
management:
  endpoints:
    web:
      exposure: 
        include: "*"
health:
  config:
    enabled: false
